RMHedon/RMHedon/Models/ErrorViewModel.cs
namespace RMHedon.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RMHedon/RMHedon/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

using RMHedon.datamodels;
using RMHedon.Services;
using RMHedon.viewmodels;

namespace RMHedon.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService categoryService;
        private int IdUser = 1;

        public CategoryController(CategoryService _categoryService)
        {
            categoryService = _categoryService;

        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<MMenuCategory> data = await categoryService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Namecategory.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Namecategory).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Namecategory).ToList();
                    break;
            }
            return View(PaginatedList<MMenuCategory>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 5));
        }

        public async Task<IActionResult> Create()
        {
            return PartialView();
        }
        public async Task<JsonResult> CheckNameIsExist(string namecategory, long id)
        {
            bool isExist = await categoryService.CheckNameIsExist(namecategory, id);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(MMenuCategory dataParam)
        {
            dataParam.CreatedBy = IdUser;
            VMResponse respon = await categoryService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Edit(long id)
        {

            VMMMenuCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMMMenuCategory dataParam)
        {
            dataParam.ModifiedBy = IdUser;

            VMResponse respon = await categoryService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMMMenuCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(VMMMenuCategory dataParam)
        {
            dataParam.DeletedBy = IdUser;

            VMResponse respon = await categoryService.Delete(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

RMHedon/RMHedon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

using RMHedon.Models;

using System.Diagnostics;

namespace RMHedon.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RMHedon/RMHedon/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;

using RMHedon.datamodels;
using RMHedon.Services;
using RMHedon.viewmodels;

namespace RMHedon.Controllers
{
    public class VariantController : Controller
    {
        private VariantService variantService;
        private CategoryService categoryService;

        private int IdUser = 1;

        public VariantController(VariantService _variantService, CategoryService _categoryService)
        {
            variantService = _variantService;
            categoryService = _categoryService;

        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<VMMMenuVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Namevariant.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Namevariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Namevariant).ToList();
                    break;
            }
            return View(PaginatedList<VMMMenuVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 5));
        }

        public async Task<IActionResult> Create()
        {
            VMMMenuVariant data = new VMMMenuVariant();

            // get all data master kategori disini...
            List<MMenuCategory> listCategories = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategories;

            return PartialView(data);
        }

        public async Task<JsonResult> CheckNameIsExist(string namevariant, long id, long idCategory)
        {
            bool isExist = await variantService.CheckNameIsExist(namevariant, id, idCategory);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMMMenuVariant dataParam)
        {

            VMResponse respon = await variantService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(long id)
        {
            VMMMenuVariant data = await variantService.GetDataById(id);

            List<MMenuCategory> listCategories = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategories;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMMMenuVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Delete(long id)
        {
            VMMMenuVariant data = await variantService.GetDataById(id);

            List<MMenuCategory> listCategories = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategories;


            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(VMMMenuVariant dataParam)
        {
            dataParam.DeletedBy = IdUser;

            VMResponse respon = await variantService.Delete(dataParam);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }



    }
}

RMHedon/RMHedon/Views/Category/Create.cshtml
<div class="card">
    <div class="card-body">
        <form class="mt-4" id="form_createCategory">

            <div class="mb-3">
                <label for="Namecategory" class="form-label">Category Name*</label>
                <input type="text" class="form-control" id="Namecategory" name="Namecategory">
                <span id="validate_Namecategory" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="Description" class="form-label">Description</label>
                <input type="text" class="form-control" id="Description" name="Description">
                <span id="validate_Description" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a class="btn btn-light" asp-controller="Category" asp-action="Index">Cancel</a>
                <button type="submit" class="btn btn-primary btn-block" id="btn_submit">Save</button>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_createCategory").validate({
        errorClass: "text-danger",
        rules: {
            Namecategory: "required",
            Description: {
                minlength: 10,
                maxlength: 100,
            }
        },
        messages: {
            Namecategory: "Please insert name",
            Description: {
                minlength: "Description must contain 10 - 100 Character",
                maxlength: "Description must contain 10 - 100 Character",
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var namecategory = $("#Namecategory").val()
            var description = $("#Description").val()
            var id = 0
            $.ajax({
                url: "/Category/CheckNameIsExist",
                type: "get",
                data: { namecategory: namecategory},
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        toastr.error(
                            'Pastikan data sudah benar',
                            'Data tidak valid',
                        )
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })

    function fungsiSubmit(dataParam) {

        $.ajax({
            url: "/Category/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {

                    toastr.success(
                        'Create Category Success',
                        'Add Category Success',
                    )
                    $("#my_modal").modal("hide")


                    setTimeout(function () {
                        window.location.reload()
                    }, 1500)
                }
                else {
                    toastr.error(
                        'Create Category Failed',
                        'Add Category Failed',
                    )
                }

            }
        })
    }

</script>

RMHedon/RMHedon/Views/Category/Delete.cshtml
@using RMHedon.viewmodels;
@model VMMMenuCategory

<div class="card">
    <div class="card-body">

        <h6>Apakah anda yakin akan menghapus data berikut ?</h6>
        <form class="mt-4" id="form_hapusCategory">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id" />

            <div class="mb-3">
                <label for="Namecategory" class="form-label">Category Name*</label>
                <input type="text" class="form-control" id="Namecategory" name="Namecategory" value="@Model.Namecategory" readonly>
                <span id="validate_Namebank" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="Description" class="form-label">Description</label>
                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
            </div>

            <div class="text-end">
                <a class="btn btn-light" asp-controller="Category" asp-action="Index">Batal</a>
                <button type="submit" class="btn btn-danger btn-block">Hapus</button>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_hapusCategory").validate({
        submitHandler: function (form) {
            var dataForm = $(form).serialize()
            var namecategory = $("#Namecategory").val()
            var id = $("#Id").val()

            $.ajax({
                url: "/Category/SureDelete",
                type: "post",
                data: dataForm,
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        toastr.success(
                            'Data Kategori berhasil dihapus',
                            'Hapus Kategori berhasil',
                        )
                        $("#my_modal").modal("hide")


                        setTimeout(function () {
                            window.location.reload()
                        }, 1500)

                    }
                    else {
                        toastr.error(
                            'Pastikan data sudah benar',
                            'Data tidak valid',
                        )
                    }

                }

            })
        }
    })
</script>

RMHedon/RMHedon/Views/Category/Edit.cshtml
@using RMHedon.viewmodels;

@model VMMMenuCategory


<div class="card">
    <div class="card-body">
        <form class="mt-4" id="form_editCategory">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id" />

            <div class="mb-3">
                <label for="Namecategory" class="form-label">Category Name*</label>
                <input type="text" class="form-control" id="Namecategory" name="Namecategory" value="@Model.Namecategory">
                <span id="validate_Namecategory" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="Description" class="form-label">Description</label>
                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
            </div>

            <div class="text-end">
                <a class="btn btn-light" asp-controller="Category" asp-action="Index">Batal</a>
                <button type="submit" class="btn btn-primary btn-block">Simpan</button>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_editCategory").validate({
        errorClass: "text-danger",
        rules: {
            Namecategory: "required",
            Description: {
                minlength: 10,
                maxlength: 100,
            }
        },
        messages: {
            Namecategory: "Please insert name",
            Description: {
                minlength: "Description must contain 10 - 100 Character",
                maxlength: "Description must contain 10 - 100 Character",
            }
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()
            var namecategory = $("#Namecategory").val()
            var description = $("#Description").val()
            var id = $("#Id").val()
            $.ajax({
                url: "/Category/CheckNameIsExist",
                type: "get",
                data: { namecategory: namecategory, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        toastr.error(
                            'Data telah tersedia',
                            'Data tidak boleh sama',
                        )
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Category/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {

                    toastr.success(
                        'Kategori berhasil diubah',
                        'Edit Data Kategori berhasil',
                    )
                    $("#my_modal").modal("hide")


                    setTimeout(function () {
                        window.location.reload()
                    }, 1500)
                }
                else {
                    toastr.error(
                        'Gagal Mengubah Data',
                        'Error',
                    )
                }

            }
        })
    }




</script>

RMHedon/RMHedon/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Rumah Makan Hedon</h1>
    <p>CITARASA NUSANTARA, SENSASI BINTANG LIMA</p>
</div>

RMHedon/RMHedon/Views/Shared/_Sidebar.cshtml
 <!-- Sidebar Start -->
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
            <a href="../Home/Index" class="text-nowrap logo-img">
                <span>Rumah Makan HEDON</span>
            </a>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                <i class="ti ti-x fs-8"></i>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">

                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Home</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" href="../Home/Index" aria-expanded="false">
                        <span>
                            <i class="ti ti-layout-dashboard"></i>
                        </span>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>

                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Master Menu</span>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" href="../Category/Index" aria-expanded="false">
                        <span>
                            <i class="bi bi-grid-1x2-fill"></i>
                        </span>
                        <span class="hide-menu">Category</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Variant" asp-action="Index" aria-expanded="false">
                        <span>
                            <i class="bi bi-grid-1x2-fill"></i>
                        </span>
                        <span class="hide-menu">Variant</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" href="./ui-card.html" aria-expanded="false">
                        <span>
                            <i class="bi bi-grid-1x2-fill"></i>
                        </span>
                        <span class="hide-menu">Product</span>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!--  Sidebar End -->

RMHedon/RMHedon/Views/Variant/Create.cshtml
@using RMHedon.viewmodels;


@model VMMMenuVariant
@{
    ViewData["Title"] = "Create Variant";
}
<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_AddVariant">
            <div class="mb-4 row">
                <label for="Namevariant" class="col-sm-4 col-form-label">Variant Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Namevariant" name="Namevariant">
                    <span id="validate_Namevariant" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Category Name</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "Namecategory"),
                    "--Select Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <div class="text-end">
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Cancel</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>


    </div>
</div>

<script>
    $("#form_AddVariant").validate({
        errorClass: "text-danger",
        rules: {
            Namevariant: {
                required: true,
                minlength: 3,
            },
            IdCategory: "required"
        },
        messages: {
            Namevariant: {
                required: "Please insert Variant Name",
                minlength: "min 3 characters",
            },
            IdCategory: "Please select Category"
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize();
            var namevariant = $("#Namevariant").val()
            var id = 0
            var idCategory = $("#IdCategory").val()

            $.ajax({
                url: "/Variant/CheckNameIsExist",
                type: "get",
                data: { namevariant: namevariant, id: id, idCategory: idCategory },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_Namevariant").text("Variant Name is already exist")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }
            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Variant/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {

                    toastr.success(
                        'Create Variant Success',
                        'Add Variant Success',
                    )
                    $("#my_modal").modal("hide")


                    setTimeout(function () {
                        window.location.reload()
                    }, 1500)
                }
                else {
                    toastr.error(
                        'Create Variant Failed',
                        'Add Variant Failed',
                    )
                }

            }
        })
    }
</script>

RMHedon/RMHedon/Views/Variant/Delete.cshtml
@using RMHedon.viewmodels;

@model VMMMenuVariant

@{
    ViewData["Title"] = "Delete Variant";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Delete" method="post" id="form_DeleteVariant">

            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

            <div class="mb-4 row">
                <label for="Namevariant" class="col-sm-4 col-form-label">Variant Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Namevariant" name="Namevariant" value="@Model.Namevariant" readonly>
                    <span id="validate_Namevariant" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Category Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Namecategory" name="Namecategory" value="@Model.Namecategory" readonly>
                    <span id="validate_Namevariant" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <div class="text-end">
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Cancel</a>
                    <button type="submit" class="btn btn-primary">Delete</button>
                </div>
            </div>
        </form>


    </div>
</div>


<script>
    $("#form_DeleteVariant").validate({
        submitHandler: function (form) {

            var dataForm = $(form).serialize();
            var namevariant = $("#Namevariant").val()
            var id = $("#Id").val()
            var idCategory = $("#IdCategory").val()

            $.ajax({
                url: "/Variant/SureDelete",
                type: "post",
                data: dataForm,
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {

                        toastr.success(
                            'Delete Variant Success',
                            'Success',
                        )
                        $("#my_modal").modal("hide")


                        setTimeout(function () {
                            window.location.reload()
                        }, 1500)
                    }
                    else {
                        toastr.error(
                            'Delete Variant Failed',
                            'Failed',
                        )
                    }

                }
            })
        }
    })


</script>

RMHedon/RMHedon/Views/Variant/Edit.cshtml
@using RMHedon.viewmodels;

@model VMMMenuVariant

@{
    ViewData["Title"] = "Edit Variant";
}
<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post" id="form_EditVariant">

            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

            <div class="mb-4 row">
                <label for="Namevariant" class="col-sm-4 col-form-label">Variant Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Namevariant" name="Namevariant" value="@Model.Namevariant">
                    <span id="validate_Namevariant" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Category Name</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "Namecategory"),
                    "--Select Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <div class="text-end">
                    <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Cancel</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>


    </div>
</div>


<script>
    $("#form_EditVariant").validate({
        errorClass: "text-danger",
        rules: {
            Namevariant: {
                required: true,
                minlength: 3,
            },
            IdCategory: "required"
        },
        messages: {
            Namevariant: {
                required: "Please insert Variant Name",
                minlength: "min 3 characters",
            },
            IdCategory: "Please select Category"
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize();
            var namevariant = $("#Namevariant").val()
            var id = 0
            var idCategory = $("#IdCategory").val()

            $.ajax({
                url: "/Variant/CheckNameIsExist",
                type: "get",
                data: { namevariant: namevariant, id: id, idCategory: idCategory },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_Namevariant").text("Variant Name is already exist")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }
            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Variant/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {

                    toastr.success(
                        'Edit Variant Success',
                        'Add Variant Success',
                    )
                    $("#my_modal").modal("hide")


                    setTimeout(function () {
                        window.location.reload()
                    }, 1500)
                }
                else {
                    toastr.error(
                        'Edit Variant Failed',
                        'Add Variant Failed',
                    )
                }

            }
        })
    }

</script>